### ISSUE TITLE
Build fails on Ubuntu 22.04 

### ISSUE THREAD

**Issue by symdeb** [free-audio/clap-host#14]
# Problem

Build fails using the instructions for Linux as provided 

# How to reproduce

`git clone --recurse-submodules https://github.com/free-audio/clap-host`
`git fetch`
`git pull origin` (up to date)

# Changes made

`sudo apt-get install ninja-build`
`sudo apt-get install gettext`
`sudo apt-get install bison `
`sudo apt-get install autoconf`

make build file executable:
`cd scripts`
`chmod +x build.sh`
`cd ..`
`scripts/build.sh`

# Result 
error: building libb2:x64-linux-clap-host failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libb2
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libb2]+Build+error
Include '[libb2] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-06-15-b0f08e40f8e8752dd0b260138ee078bd9599559c
    vcpkg-scripts version: ac6ef2f66 2022-06-15 (2 days ago)

You can also use the prefilled template from  clap/clap-host/vcpkg/installed/vcpkg/issue_body.md.

# Solution

1. Run 

`sudo apt update && sudo apt upgrade && sudo apt install build-essential gperf ninja-build cmake libgl1-mesa-dev libfontconfig1-dev libfreetype6-dev libx11-dev libx11-xcb-dev  libxcb-damage0-dev libxcb-dpms0-dev libxcb-glx0-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev  libxcb-present-dev  libxcb-randr0-dev libxcb-record0-dev libxcb-render-util0-dev libxcb-render0-dev libxcb-res0-dev libxcb-shape0-dev libxcb-shm0-dev libxcb-sync-dev libxcb-util-dev libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-xkb-dev libxcb1-dev libxext-dev       libxfixes-dev libxi-dev  libxkbcommon-dev libxkbcommon-x11-dev libxrender-dev libatspi2.0-dev`

2. Replace vcpkg  (subdirectory of the repo)

`rm -r vcpkg`
`git clone https://github.com/microsoft/vcpkg`
`./vcpkg/bootstrap-vcpkg.sh`

**Comment by abique** [comment]
The github actions also runs on ubuntu.
See https://github.com/free-audio/clap-host/blob/main/.github/workflows/build.yml#L81

**Comment by symdeb** [comment]
Thanks. but,the question was about building it on a an on-premises ubuntu desktop/server instead of the Github CI.
Edited the solution as above et voila !

![Screenshot from 2022-06-18 23-47-01](https://user-images.githubusercontent.com/19564066/174446217-a8cc5f75-6d53-4003-8e21-bac2883fe9ab.png)

Issue can be closed
