### ISSUE TITLE
Linux dynamic build fails on first cmake step

### ISSUE THREAD

**Issue by sowbug** [free-audio/clap-host#16]
Ubuntu 20.04

```
$ cd clap-plugins/
$ cmake --preset ninja-system
CMake Error: The source directory "./src/clap-plugins/ninja-system" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
```

I don't know enough about cmake or ninja to know what's supposed to happen next. The same error happens with the `clap-plugins` project.

**Comment by abique** [comment]
Hi,
Which version of cmake are you using? I suppose that your version is a bit old and you may be able to fix it by updating your tools.
Sorry I haven't tried on ubuntu 20.04.
I have cmake 3.23.2.
Regards,
Alex

**Comment by sowbug** [comment]
```
$ cmake --version
cmake version 3.16.3
```

This is the default provided by Ubuntu 20.04, which until two months ago was the newest long-term-support version of the distro. It looks like cmake doesn't know what `CMakePresets.json` is [until cmake 3.19](https://cmake.org/cmake/help/latest/release/3.19.html). I temporarily downloaded the latest cmake (3.23.2) and got past the `--preset` issue, but am now getting an error about Qt6. Ubuntu 20.04's repos include only Qt 5, and https://www.qt.io/ is posing a lot of license/legalese questions/options before it's willing to give me the Qt 6 development libraries. This is too much for a Sunday morning before my coffee has kicked in.

Thank you for building and maintaining this project. I don't think Ubuntu 20.04 users are within the set of developers it is targeting.
