### ISSUE TITLE
Incomplete build instructions for Windows

### ISSUE THREAD

**Issue by fluxehub** [free-audio/clap-host#26]
I tried to build this for a project I'm currently working on, noticed that the current instructions for Windows ends with running `build.sh`, which is not possible, as `build.sh` is a bash script and therefore not compatible with PowerShell. Are there updated build instructions?

**Comment by Arakula** [comment]
I think the documentation should mention that you need to have Git for Windows installed for that to work.

**Comment by gentoid** [comment]
I've managed it to run with `bash scripts/build.sh`

**Comment by abique** [comment]
I tried recently and `git-bash` managed to build it on Windows.
I've updated the build instructions, please try again.
