### ISSUE TITLE
Feature request: type-to-MIDI (or equivalent)

### ISSUE THREAD

**Issue by nakst** [free-audio/clap-host#9]
I'm trying to port my plugin to CLAP beta, and I've built the clap-host project on Linux and it loads and I get audio output, but I don't have a way to send MIDI note on/off to my plugin. My feature request is that there is a way to use the typing keyboard to simulate MIDI note on/off events, as in available in many DAWs. This is currently a roadblock for me with porting my plugin, so I think it is important to add this feature as it will probably be a roadblock for other developers. There could also be another alternative method for simulating note on/off, such as with GUI buttons.

**Comment by abique** [comment]
Good idea!
The keyboard is tricky due to various keyboard layout.
A widget for showing some keys could be helpful.
Do you have a midi controller?

**Comment by nakst** [comment]
My MIDI controller is broken. Which is kind of the problem :)
